# Generated by Django 2.2.3 on 2020-01-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s_no',
            field=models.IntegerField(default=2),
        ),
    ]
