# Generated by Django 2.2.3 on 2020-01-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_user_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='s_no',
        ),
    ]
