# Generated by Django 2.2.3 on 2020-01-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_myuser_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
